// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://yhahrnadvnwpztpiuoed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InloYWhybmFkdm53cHp0cGl1b2VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5ODQ3NTcsImV4cCI6MjA3MzU2MDc1N30.aTQTVNdDG5hYtEEPfGZNAAqW1orlaeTXcZrRxbOzV-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});